### PR TITLE
Merge my changes to upstream

### PR DESCRIPTION
**Pull request by lychichem**
I think now is the time to merge.
This add 2 feature and fix 1 issue to your code.
Feature 1: Support titlebar to change color according to system theme on at least Win 10 10525 and later (According to code may also work on windows 8).
Feature 2: Remove warning about "add-on not signed and take care". 
Fix: Checked mark in checkbox on HTML pages should now work properly.

### CODE REVIEW

**Comment by johngraciliano** [comment]
I am glad you bring this.  I was about to ask you for the changes you did to _browser.css_.  I would like those to be included this theme before it gets reviewed by AMO.  I am, however, a bit hesitant about the other changes because:
1. (Re: _extensions.css_) Security warnings should not be hidden by default.  Hiding them has to be a decision of the user, who can always customize the theme with tools like _Stylish_ (the addon).*   If there is a problem with warnings showing when they should not, I am unaware of that, please let me know.**  Yet if a warning is to bothersome, a change may be a good thing, but I would not hide it by default.
2.  (Re: _common.css_) I am worried about the side effects of using `!important.`  I only use it after finding it is unavoidable because someone did not have the time to clean that trap from the code before.  Yet I have found those traps and I have made the code a bit dirtier.

I will do a (partial?) merge as soon as I am clear of what I am doing.

---

*I customize _Simple White X_ beyond what I update. E.g., I do not like the perspective in the new tab page nor I like the tiles aspect ratio [proportions/size] and I change them with _Stylish_.  But I cannot push that on other users. Yet I am guilty of making a button show in the _Developers Tools_ that is hidden by default.
**I hardly ever use the default theme, thus I may unaware of some defaults.

**Comment by lychichem** [comment]
1. For warning, it only removes warnings about unsigned add-on, and doesn't touch any other warnings. If users use add-on from AMO, they can't install not signed add-on. And if they don't change the configure xpinstall.signatures.required to true, they cannot install unsigned add-on from other sites. Users who knows how to change the value may be considered as power users. And ordinary users don't like to see this warning. I can confirm it in forums about Firefox.
2. Don't worry about the !important used here as Mozilla themselves also used it here.

**Comment by lychichem** [comment]
But someone in forum mentioned just now that if I add the feature of hiding warnings of unsigned add-on, it may take longer time for AMO editors to review it. Maybe we should consider it.

**Comment by johngraciliano** [comment]
I have extensions that produce different warnings in Firefox 41.0.1, as a sample:
- Free Download Manager plugin is incompatible with Firefox 41.0.1.
- Quick Translator is know to cause security or stability issues.  _More information_
- uBlock could not be verified for use in Firefox. Proceed with caution. _More information_

The last is the one related to unsigned extensions, but all warnings disappear with the change in _extensions.css._  I want to see all of them.

As I stated, customizing the theme can be achieved easily with the _Stylish_ extension.  I will (eventually) provide links to _styles_ (css files!) that can be applied with _Stylish_ so that any theme user could customize it at will.

**Comment by lychichem** [comment]
Okay, Later I also realized that if we remove the warning AMO editors may not let this theme pass the review. Just do what you want. I'll help make a better style. As for FDM, don't you know it updated its Firefox add-on? You can update your FDM to 3.9.6.1614 to get it. Remember to remove former FDM extension before you install the new FDM.

**Comment by johngraciliano** [comment]
The changes you made to browser.css are specific to Windows 10 (or later!).  I trust you tested they have no ill effects when not using the colorful titlebar.  So I will merge the changes for common.css and browser.css.  As agreed, hiding the warnings cannot make it into the theme, but I will provide links to attain that and a few other custmizations easily (eventually!).
Thanks for the tip about FDM, I will update.  However I prefer not to use the extension and set my downloads through alternate means (e.g., via the drop box) when I use it (it is not often).

**Comment by lychichem** [comment]
I'm not familiar with @media （if I mistakenly called someone I'll say sorry) rules. When changing it I have to use style editor in F12 tool. Happy to hear that it will not have side effect to Windows 7 or former system.

**Comment by johngraciliano** [comment]
I am not familiar with _Windows 10_ so we are even.  Thank you for the help.  
Now I have to see how I fix the mess I made for the _Apple_ implementation.  I hope someone volunteers for testing.   I also have to complete the implementation of the _radioactive_ icon.

**Pull request merged**
